# Spam Identifier model

In [22]:
import pandas as pd

data = pd.read_csv('SMSSpamCollection', sep='\t', names=['label', 'message'])


In [48]:
data

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [26]:
import nltk

nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\manis\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [31]:
from nltk.corpus import stopwords
import re

In [60]:
from nltk import WordNetLemmatizer

lm=WordNetLemmatizer()

In [61]:
corpus=[]

for i in range(len(data)):
    msg=re.sub('[^a-zA-Z]',' ', data['message'][i])
    review=[lm.lemmatize(word.lower()) for word in msg.split() if not word in set(stopwords.words('english'))]
    rev=' '.join(review)
    corpus.append(rev)
    
    
  



In [62]:
corpus

['go jurong point crazy available bugis n great world la e buffet cine got amore wat',
 'ok lar joking wif u oni',
 'free entry wkly comp win fa cup final tkts st may text fa receive entry question std txt rate t c apply',
 'u dun say early hor u c already say',
 'nah i think go usf life around though',
 'freemsg hey darling week word back i like fun still tb ok xxx std chgs send rcv',
 'even brother like speak they treat like aid patent',
 'a per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune',
 'winner a valued network customer selected receivea prize reward to claim call claim code kl valid hour',
 'had mobile month u r entitled update latest colour mobile camera free call the mobile update co free',
 'i gonna home soon want talk stuff anymore tonight k i cried enough today',
 'six chance win cash from pound txt csh send cost p day day tsandcs apply reply hl info',
 'urgent you week free membership prize jackpot txt word cla

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
#max_feature : features selection for bag of words
#ngrams : feature creation by using multiple columns
#binary : vectorizer produced binary vector (0 and 1)


vectorizer=CountVectorizer(max_features=100 ,ngram_range=(2,2), binary=True)
X=vectorizer.fit_transform(corpus)
X

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2077 stored elements and shape (5572, 100)>

In [65]:
X.shape

(5572, 2500)

In [68]:
print(X.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [71]:
vectorizer.vocabulary_

{'free entry': np.int64(31),
 'to claim': np.int64(81),
 'claim call': np.int64(15),
 'call claim': np.int64(3),
 'free call': np.int64(30),
 'chance win': np.int64(14),
 'txt word': np.int64(85),
 'let know': np.int64(53),
 'please call': np.int64(65),
 'lt gt': np.int64(57),
 'want go': np.int64(92),
 'like lt': np.int64(54),
 'sorry call': np.int64(75),
 'call later': np.int64(8),
 'ur awarded': np.int64(86),
 'how much': np.int64(48),
 'hi hi': np.int64(45),
 'call customer': np.int64(4),
 'customer service': np.int64(22),
 'cash prize': np.int64(13),
 'po box': np.int64(67),
 'we trying': np.int64(94),
 'trying contact': np.int64(82),
 'draw show': np.int64(28),
 'show prize': np.int64(74),
 'prize guaranteed': np.int64(69),
 'guaranteed call': np.int64(40),
 'valid hr': np.int64(90),
 'selected receive': np.int64(71),
 'private your': np.int64(68),
 'your account': np.int64(98),
 'account statement': np.int64(0),
 'statement show': np.int64(76),
 'call identifier': np.int64(5),
 